# Generated by Django 4.2 on 2025-04-20 12:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        max_length=123,
                        null=True,
                        unique=True,
                        verbose_name="username",
                    ),
                ),
                (
                    "fullname",
                    models.CharField(
                        blank=True, max_length=123, null=True, verbose_name="fullname"
                    ),
                ),
                (
                    "firstname",
                    models.CharField(
                        blank=True, max_length=123, null=True, verbose_name="firstname"
                    ),
                ),
                (
                    "lastname",
                    models.CharField(
                        blank=True, max_length=123, null=True, verbose_name="lastname"
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        default="uz", max_length=5, verbose_name="language"
                    ),
                ),
                (
                    "telegram_id",
                    models.CharField(
                        max_length=55, unique=True, verbose_name="telegram id"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="phone number"
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        blank=True, max_length=125, null=True, verbose_name="password"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("admin", "Admin"),
                            ("asistent", "Asistent"),
                        ],
                        default="user",
                        max_length=55,
                        verbose_name="role",
                    ),
                ),
                ("ordered", models.BooleanField(default=True)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Create at"),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
        ),
    ]
