# Generated by Django 4.2 on 2025-04-26 05:08

import shop.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_user_photo_alter_user_ordered_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="telegram_link",
            field=models.URLField(
                default=1, validators=[shop.validators.validate_telegram_url]
            ),
            preserve_default=False,
        ),
    ]
