# Generated by Django 4.2 on 2025-04-26 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_user_telegram_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="telegram_link",
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("customer", "Customer"), ("seller", "Seller")],
                default="customer",
                max_length=55,
                verbose_name="role",
            ),
        ),
    ]
