# Generated by Django 4.2 on 2025-04-28 10:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_remove_user_telegram_link_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groups",
            name="users",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="user_groups",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
