# Generated by Django 4.2 on 2025-05-01 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0007_alter_groups_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="notification",
            field=models.BooleanField(default=True),
        ),
    ]
